// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Dnssec extends pulumi.CustomResource {
    /**
     * Get an existing Dnssec resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DnssecState, opts?: pulumi.CustomResourceOptions): Dnssec {
        return new Dnssec(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'namedotcom:index/dnssec:Dnssec';

    /**
     * Returns true if the given object is an instance of Dnssec.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Dnssec {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Dnssec.__pulumiType;
    }

    /**
     * Algorithm is an integer identifying the algorithm used for signing. Changing this forces a new resource.
     */
    declare public readonly algorithm: pulumi.Output<number>;
    /**
     * Digest is a digest of the DNSKEY RR that is registered with the registry. Changing this forces a new resource.
     */
    declare public readonly digest: pulumi.Output<string>;
    /**
     * DigestType is an integer identifying the algorithm used to create the digest. Changing this forces a new resource.
     */
    declare public readonly digestType: pulumi.Output<number>;
    /**
     * DomainName is the zone that the DNSSEC belongs to. Changing this forces a new resource.
     */
    declare public readonly domainName: pulumi.Output<string>;
    /**
     * KeyTag contains the key tag value of the DNSKEY RR that validates this signature. Changing this forces a new resource.
     */
    declare public readonly keyTag: pulumi.Output<number>;

    /**
     * Create a Dnssec resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DnssecArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DnssecArgs | DnssecState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DnssecState | undefined;
            resourceInputs["algorithm"] = state?.algorithm;
            resourceInputs["digest"] = state?.digest;
            resourceInputs["digestType"] = state?.digestType;
            resourceInputs["domainName"] = state?.domainName;
            resourceInputs["keyTag"] = state?.keyTag;
        } else {
            const args = argsOrState as DnssecArgs | undefined;
            if (args?.algorithm === undefined && !opts.urn) {
                throw new Error("Missing required property 'algorithm'");
            }
            if (args?.digest === undefined && !opts.urn) {
                throw new Error("Missing required property 'digest'");
            }
            if (args?.digestType === undefined && !opts.urn) {
                throw new Error("Missing required property 'digestType'");
            }
            if (args?.domainName === undefined && !opts.urn) {
                throw new Error("Missing required property 'domainName'");
            }
            if (args?.keyTag === undefined && !opts.urn) {
                throw new Error("Missing required property 'keyTag'");
            }
            resourceInputs["algorithm"] = args?.algorithm;
            resourceInputs["digest"] = args?.digest;
            resourceInputs["digestType"] = args?.digestType;
            resourceInputs["domainName"] = args?.domainName;
            resourceInputs["keyTag"] = args?.keyTag;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Dnssec.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Dnssec resources.
 */
export interface DnssecState {
    /**
     * Algorithm is an integer identifying the algorithm used for signing. Changing this forces a new resource.
     */
    algorithm?: pulumi.Input<number | undefined>;
    /**
     * Digest is a digest of the DNSKEY RR that is registered with the registry. Changing this forces a new resource.
     */
    digest?: pulumi.Input<string | undefined>;
    /**
     * DigestType is an integer identifying the algorithm used to create the digest. Changing this forces a new resource.
     */
    digestType?: pulumi.Input<number | undefined>;
    /**
     * DomainName is the zone that the DNSSEC belongs to. Changing this forces a new resource.
     */
    domainName?: pulumi.Input<string | undefined>;
    /**
     * KeyTag contains the key tag value of the DNSKEY RR that validates this signature. Changing this forces a new resource.
     */
    keyTag?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a Dnssec resource.
 */
export interface DnssecArgs {
    /**
     * Algorithm is an integer identifying the algorithm used for signing. Changing this forces a new resource.
     */
    algorithm: pulumi.Input<number>;
    /**
     * Digest is a digest of the DNSKEY RR that is registered with the registry. Changing this forces a new resource.
     */
    digest: pulumi.Input<string>;
    /**
     * DigestType is an integer identifying the algorithm used to create the digest. Changing this forces a new resource.
     */
    digestType: pulumi.Input<number>;
    /**
     * DomainName is the zone that the DNSSEC belongs to. Changing this forces a new resource.
     */
    domainName: pulumi.Input<string>;
    /**
     * KeyTag contains the key tag value of the DNSKEY RR that validates this signature. Changing this forces a new resource.
     */
    keyTag: pulumi.Input<number>;
}
