// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { DnssecArgs, DnssecState } from "./dnssec";
export type Dnssec = import("./dnssec").Dnssec;
export const Dnssec: typeof import("./dnssec").Dnssec = null as any;
utilities.lazyLoad(exports, ["Dnssec"], () => require("./dnssec"));

export { DomainNameserversArgs, DomainNameserversState } from "./domainNameservers";
export type DomainNameservers = import("./domainNameservers").DomainNameservers;
export const DomainNameservers: typeof import("./domainNameservers").DomainNameservers = null as any;
utilities.lazyLoad(exports, ["DomainNameservers"], () => require("./domainNameservers"));

export * from "./provider";
import { Provider } from "./provider";

export { RecordArgs, RecordState } from "./record";
export type Record = import("./record").Record;
export const Record: typeof import("./record").Record = null as any;
utilities.lazyLoad(exports, ["Record"], () => require("./record"));


// Export sub-modules:
import * as config from "./config";

export {
    config,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "namedotcom:index/dnssec:Dnssec":
                return new Dnssec(name, <any>undefined, { urn })
            case "namedotcom:index/domainNameservers:DomainNameservers":
                return new DomainNameservers(name, <any>undefined, { urn })
            case "namedotcom:index/record:Record":
                return new Record(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("namedotcom", "index/dnssec", _module)
pulumi.runtime.registerResourceModule("namedotcom", "index/domainNameservers", _module)
pulumi.runtime.registerResourceModule("namedotcom", "index/record", _module)
pulumi.runtime.registerResourcePackage("namedotcom", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:namedotcom") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
