// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The provider type for the namedotcom package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'namedotcom';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * Name.com API Token Value; can alternatively be specified via the `NAMEDOTCOM_TOKEN` environment variable.
     */
    declare public readonly token: pulumi.Output<string | undefined>;
    /**
     * Name.com API Username; can alternatively be specified via the `NAMEDOTCOM_USERNAME` environment variable.
     */
    declare public readonly username: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            resourceInputs["rateLimitPerHour"] = pulumi.output(args?.rateLimitPerHour).apply(JSON.stringify);
            resourceInputs["rateLimitPerSecond"] = pulumi.output(args?.rateLimitPerSecond).apply(JSON.stringify);
            resourceInputs["timeout"] = pulumi.output(args?.timeout).apply(JSON.stringify);
            resourceInputs["token"] = args?.token ? pulumi.secret(args.token) : undefined;
            resourceInputs["username"] = args?.username;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Provider.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }

    /**
     * This function returns a Terraform config object with terraform-namecased keys,to be used with the Terraform Module Provider.
     */
    terraformConfig(): pulumi.Output<{[key: string]: any}> {
        const result: pulumi.Output<Provider.TerraformConfigResult> = pulumi.runtime.call("pulumi:providers:namedotcom/terraformConfig", {
            "__self__": this,
        }, this, utilities.getPackage());
        return result.result;
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * Maximum number of API requests per hour. Defaults to 3000.
     */
    rateLimitPerHour?: pulumi.Input<number | undefined>;
    /**
     * Maximum number of API requests per second. Defaults to 20.
     */
    rateLimitPerSecond?: pulumi.Input<number | undefined>;
    /**
     * Timeout in seconds for API requests. Defaults to 120 seconds.
     */
    timeout?: pulumi.Input<number | undefined>;
    /**
     * Name.com API Token Value; can alternatively be specified via the `NAMEDOTCOM_TOKEN` environment variable.
     */
    token?: pulumi.Input<string | undefined>;
    /**
     * Name.com API Username; can alternatively be specified via the `NAMEDOTCOM_USERNAME` environment variable.
     */
    username?: pulumi.Input<string | undefined>;
}

export namespace Provider {
    /**
     * The results of the Provider.terraformConfig method.
     */
    export interface TerraformConfigResult {
        readonly result: {[key: string]: any};
    }

}
