// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Record extends pulumi.CustomResource {
    /**
     * Get an existing Record resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RecordState, opts?: pulumi.CustomResourceOptions): Record {
        return new Record(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'namedotcom:index/record:Record';

    /**
     * Returns true if the given object is an instance of Record.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Record {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Record.__pulumiType;
    }

    /**
     * Answer is the record value: the IP address for A and AAAA records, the target for ANAME, CNAME, MX, NS, and SRV records, or the text for TXT records.
     */
    declare public readonly answer: pulumi.Output<string | undefined>;
    /**
     * DomainName is the zone that the record belongs to. Changing this forces a new resource.
     */
    declare public readonly domainName: pulumi.Output<string | undefined>;
    /**
     * Host is the hostname relative to the zone.
     */
    declare public readonly host: pulumi.Output<string | undefined>;
    /**
     * Priority is used by MX and SRV records, where a lower value is preferred; it is ignored for all other record types. Valid range is 0-65535.
     */
    declare public readonly priority: pulumi.Output<number | undefined>;
    /**
     * Unique record id assigned by Name.com (numeric form of <span pulumi-lang-nodejs="`id`" pulumi-lang-dotnet="`Id`" pulumi-lang-go="`id`" pulumi-lang-python="`id`" pulumi-lang-yaml="`id`" pulumi-lang-java="`id`" pulumi-lang-hcl="`id`">`id`</span>).
     */
    declare public /*out*/ readonly recordId: pulumi.Output<number>;
    /**
     * Type is one of the following: A, AAAA, ANAME, CNAME, MX, NS, SRV, or TXT. Changing this forces a new resource.
     */
    declare public readonly recordType: pulumi.Output<string | undefined>;

    /**
     * Create a Record resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: RecordArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RecordArgs | RecordState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RecordState | undefined;
            resourceInputs["answer"] = state?.answer;
            resourceInputs["domainName"] = state?.domainName;
            resourceInputs["host"] = state?.host;
            resourceInputs["priority"] = state?.priority;
            resourceInputs["recordId"] = state?.recordId;
            resourceInputs["recordType"] = state?.recordType;
        } else {
            const args = argsOrState as RecordArgs | undefined;
            resourceInputs["answer"] = args?.answer;
            resourceInputs["domainName"] = args?.domainName;
            resourceInputs["host"] = args?.host;
            resourceInputs["priority"] = args?.priority;
            resourceInputs["recordType"] = args?.recordType;
            resourceInputs["recordId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Record.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Record resources.
 */
export interface RecordState {
    /**
     * Answer is the record value: the IP address for A and AAAA records, the target for ANAME, CNAME, MX, NS, and SRV records, or the text for TXT records.
     */
    answer?: pulumi.Input<string | undefined>;
    /**
     * DomainName is the zone that the record belongs to. Changing this forces a new resource.
     */
    domainName?: pulumi.Input<string | undefined>;
    /**
     * Host is the hostname relative to the zone.
     */
    host?: pulumi.Input<string | undefined>;
    /**
     * Priority is used by MX and SRV records, where a lower value is preferred; it is ignored for all other record types. Valid range is 0-65535.
     */
    priority?: pulumi.Input<number | undefined>;
    /**
     * Unique record id assigned by Name.com (numeric form of <span pulumi-lang-nodejs="`id`" pulumi-lang-dotnet="`Id`" pulumi-lang-go="`id`" pulumi-lang-python="`id`" pulumi-lang-yaml="`id`" pulumi-lang-java="`id`" pulumi-lang-hcl="`id`">`id`</span>).
     */
    recordId?: pulumi.Input<number | undefined>;
    /**
     * Type is one of the following: A, AAAA, ANAME, CNAME, MX, NS, SRV, or TXT. Changing this forces a new resource.
     */
    recordType?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Record resource.
 */
export interface RecordArgs {
    /**
     * Answer is the record value: the IP address for A and AAAA records, the target for ANAME, CNAME, MX, NS, and SRV records, or the text for TXT records.
     */
    answer?: pulumi.Input<string | undefined>;
    /**
     * DomainName is the zone that the record belongs to. Changing this forces a new resource.
     */
    domainName?: pulumi.Input<string | undefined>;
    /**
     * Host is the hostname relative to the zone.
     */
    host?: pulumi.Input<string | undefined>;
    /**
     * Priority is used by MX and SRV records, where a lower value is preferred; it is ignored for all other record types. Valid range is 0-65535.
     */
    priority?: pulumi.Input<number | undefined>;
    /**
     * Type is one of the following: A, AAAA, ANAME, CNAME, MX, NS, SRV, or TXT. Changing this forces a new resource.
     */
    recordType?: pulumi.Input<string | undefined>;
}
