// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("namedotcom");

/**
 * Maximum number of API requests per hour. Defaults to 3000.
 */
export declare const rateLimitPerHour: number | undefined;
Object.defineProperty(exports, "rateLimitPerHour", {
    get() {
        return __config.getObject<number>("rateLimitPerHour");
    },
    enumerable: true,
});

/**
 * Maximum number of API requests per second. Defaults to 20.
 */
export declare const rateLimitPerSecond: number | undefined;
Object.defineProperty(exports, "rateLimitPerSecond", {
    get() {
        return __config.getObject<number>("rateLimitPerSecond");
    },
    enumerable: true,
});

/**
 * Timeout in seconds for API requests. Defaults to 120 seconds.
 */
export declare const timeout: number | undefined;
Object.defineProperty(exports, "timeout", {
    get() {
        return __config.getObject<number>("timeout");
    },
    enumerable: true,
});

/**
 * Name.com API Token Value; can alternatively be specified via the `NAMEDOTCOM_TOKEN` environment variable.
 */
export declare const token: string | undefined;
Object.defineProperty(exports, "token", {
    get() {
        return __config.get("token");
    },
    enumerable: true,
});

/**
 * Name.com API Username; can alternatively be specified via the `NAMEDOTCOM_USERNAME` environment variable.
 */
export declare const username: string | undefined;
Object.defineProperty(exports, "username", {
    get() {
        return __config.get("username");
    },
    enumerable: true,
});

