export const MUSCLE_GROUPS = [
  "Abductors",
  "Adductors",
  "Abdominals",
  "Obliques",
  "Biceps",
  "Chest",
  "Calves",
  "Forearms",
  "Glutes",
  "Hamstrings",
  "Lats",
  "Lower Back",
  "Middle Back",
  "Upper Back",
  "Quadriceps",
  "Shoulders",
  "Trapezius",
  "Triceps",
  "Front Deltoid",
  "Middle Deltoid",
  "Rear Deltoid"
] as const

//map muscle name -> diagram region id/class
export const MUSCLE_REGION_MAP: Record<string, string> = {
  Abdominals: "region-abdominals",
  Obliques: "region-obliques",
  Abductors: "region-abductors",
  Adductors: "region-adductors",
  Biceps: "region-biceps",
  Chest: "region-chest",
  "Front Deltoid": "region-front-deltoid",
  "Middle Deltoid": "region-middle-deltoid",
  Quadriceps: "region-quadriceps",
  Forearms: "region-forearms",
  Calves: "region-calves",
  Glutes: "region-glutes",
  Hamstrings: "region-hamstrings",
  Lats: "region-lats",
  "Lower Back": "region-lower-back",
  "Middle Back": "region-middle-back",
  "Upper Back": "region-upper-back",
  Traps: "region-traps",
  Triceps: "region-triceps",
  "Rear Deltoid": "region-rear-deltoid"
}