services:
  worker-node:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: optivision-worker-node
    restart: unless-stopped
    volumes:
      - ./training/weights:/app/training/weights:ro
    env_file:
      - ./worker/.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

