config:
  infrastructure:postgressPassword:
    secure: AAABAPRPVvHsxbdewhXWGmSqC7nvliunkCYJIgmIXRbzi1yTL0KnxmWj6XoJEbfWXGtkrXqDBE0k
  infrastructure:jwtSecret:
    secure: AAABADxpdVSQ/FgU77ylVSsM78+UDm4ier7z8RSZrLS3JQ2M4mZ4vdK0VUj6VXdX9tKtESsZGqfMrzMy5uk/KFIrUkSdVy/2cKOO
  infrastructure:dbEncryptionKey:
    secure: AAABAA2H+rT4uVKEFwdabUlXtlJsLtf6c1xFLs+5n309guY8ByoK7z/TzzqD3un6udRxZ5fQRn6u2sNc9O3eUWn7THUf4R3dR4ZbFQ==
  infrastructure:devSeeding: "true"
  infrastructure:jwtExpMin: "1440"
  namedotcom:token:
    secure: AAABACBdbD8KnEgs+afV9EBIeRrnZXTw+QriLVpWrj9ewC2ozExjNCF173hfhthVr4dApv9zN7BJEFOvAswNCUsgwUf5aerj
  namedotcom:username: u24664155
