config:
  infrastructure:postgressPassword:
    secure: AAABAPRPVvHsxbdewhXWGmSqC7nvliunkCYJIgmIXRbzi1yTL0KnxmWj6XoJEbfWXGtkrXqDBE0k
  infrastructure:jwtSecret:
    secure: AAABADxpdVSQ/FgU77ylVSsM78+UDm4ier7z8RSZrLS3JQ2M4mZ4vdK0VUj6VXdX9tKtESsZGqfMrzMy5uk/KFIrUkSdVy/2cKOO
  infrastructure:dbEncryptionKey:
    secure: AAABAA2H+rT4uVKEFwdabUlXtlJsLtf6c1xFLs+5n309guY8ByoK7z/TzzqD3un6udRxZ5fQRn6u2sNc9O3eUWn7THUf4R3dR4ZbFQ==
  infrastructure:devSeeding: "true"
  infrastructure:jwtExpMin: "1440"
  namedotcom:token:
    secure: AAABACBdbD8KnEgs+afV9EBIeRrnZXTw+QriLVpWrj9ewC2ozExjNCF173hfhthVr4dApv9zN7BJEFOvAswNCUsgwUf5aerj
  namedotcom:username: u24664155
  infrastructure:bindDomains: "true"
  infrastructure:domainStage: bind
  infrastructure:coreApiSentryDsn:
    secure: AAABAN7B+dbp1skyqkGpzzEkSF3BxZu+jGhlGgj1HB62AKwIvXVOQCOGaRtsSjvDhRlLD78RBlvTqzjjnwuMJ4mtH7YUbNwKaQ3rFQ3IGgvl3UBQxJOztw685X18JzPzVpDfp8G2dcnZ0879gs8R+xQ9yMfHvy/TfbPKP5eRRQ==
  infrastructure:googleClientId:
    secure: AAABAFcCXrSvOxC3Ia4MFfBohHsbXrqlKYoKExcANzEDX0hrib0qy+TYUqh8L+fFyvsJoPAtvoYWvs4WGRj0ts8f++5R32wGyA/8s0plR9TERNrT6D8MsyyeEZ8ov7f6ToBNDgDyEXU=
