// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OptiLifts.Infrastructure.Database;

#nullable disable

namespace OptiLifts.Infrastructure.Migrations
{
    [DbContext(typeof(OptiLiftsDbContext))]
    [Migration("20260901185403_RemoveChronicFatigueAddRpeTrend")]
    partial class RemoveChronicFatigueAddRpeTrend
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OptiLifts.Domain.Gamification.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("badge_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text")
                        .HasColumnName("icon_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("Threshold")
                        .HasColumnType("integer")
                        .HasColumnName("threshold");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("badges", (string)null);
                });

            modelBuilder.Entity("OptiLifts.Domain.Gamification.UserBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_badge_id");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uuid")
                        .HasColumnName("badge_id");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("earned_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.HasIndex("UserId", "BadgeId")
                        .IsUnique();

                    b.ToTable("user_badges", (string)null);
                });

            modelBuilder.Entity("OptiLifts.Domain.Messaging.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_id");

                    b.Property<DateTime>("SendAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("send_at");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("OptiLifts.Domain.Training.ExerciseTrend", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("trend_id");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<float>("MeanE1rm")
                        .HasColumnType("real")
                        .HasColumnName("mean_e1rm");

                    b.Property<bool>("RpeTrendRising")
                        .HasColumnType("boolean")
                        .HasColumnName("rpe_trend_rising");

                    b.Property<int>("SessionsUsed")
                        .HasColumnType("integer")
                        .HasColumnName("sessions_used");

                    b.Property<float>("SlopeCiHigh")
                        .HasColumnType("real")
                        .HasColumnName("slope_ci_high");

                    b.Property<float>("SlopeCiLow")
                        .HasColumnType("real")
                        .HasColumnName("slope_ci_low");

                    b.Property<float>("SlopePctPerWeek")
                        .HasColumnType("real")
                        .HasColumnName("slope_pct_per_week");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersedesExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_exercise_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("WindowEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_end");

                    b.Property<DateTime>("WindowStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_start");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("SupersedesExerciseId");

                    b.HasIndex("UserId", "ExerciseId")
                        .IsUnique();

                    b.ToTable("exercise_trends", (string)null);
                });

            modelBuilder.Entity("OptiLifts.Domain.Training.TrainingEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<float?>("Confidence")
                        .HasColumnType("real")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("text")
                        .HasColumnName("diagnosis");

                    b.Property<string>("Outcome")
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<string>("Recommendation")
                        .HasColumnType("text")
                        .HasColumnName("recommendation");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("training_events", (string)null);
                });

            modelBuilder.Entity("OptiLifts.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Bio")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("text")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EmailHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("email_hash");

                    b.Property<string>("GoogleCalendarId")
                        .HasColumnType("text")
                        .HasColumnName("google_calendar_id");

                    b.Property<string>("GoogleCalendarRefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("google_calendar_refresh_token");

                    b.Property<bool>("GoogleCalendarSyncEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("google_calendar_sync_enabled");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("google_id");

                    b.Property<string>("Height")
                        .HasColumnType("text")
                        .HasColumnName("height");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<bool>("LightTheme")
                        .HasColumnType("boolean")
                        .HasColumnName("light_theme");

                    b.Property<bool>("Metric")
                        .HasColumnType("boolean")
                        .HasColumnName("metric");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("profile_image_url");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<string>("Sex")
                        .HasColumnType("text")
                        .HasColumnName("sex");

                    b.Property<string>("Weight")
                        .HasColumnType("text")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("EmailHash")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique();

                    b.HasIndex("RefreshTokenHash");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("OptiLifts.Domain.Users.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<string>("ModelPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_path");

                    b.Property<DateTime>("TrainedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trained_at");

                    b.Property<int>("TrainingSessions")
                        .HasColumnType("integer")
                        .HasColumnName("training_sessions");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_models", (string)null);
                });

            modelBuilder.Entity("OptiLifts.Domain.Workouts.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_dict_id");

                    b.Property<string>("Equipment")
                        .HasColumnType("text")
                        .HasColumnName("equipment");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exercise_type");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Mechanic")
                        .HasColumnType("text")
                        .HasColumnName("mechanic");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("PrimaryMuscleId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_muscle");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryMuscleId");

                    b.HasIndex("UserId", "IsDeleted");

                    b.ToTable("exercise_dictionary", (string)null);
                });

            modelBuilder.Entity("OptiLifts.Domain.Workouts.ExerciseGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_group_id");

                    b.Property<int>("RestTime")
                        .HasColumnType("integer")
                        .HasColumnName("rest_time");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("group_type");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("exercise_groups", (string)null);
                });

            modelBuilder.Entity("OptiLifts.Domain.Workouts.ExercisePr", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("pr_id");

                    b.Property<int>("AchievedReps")
                        .HasColumnType("integer")
                        .HasColumnName("achieved_reps");

                    b.Property<float>("AchievedWeight")
                        .HasColumnType("real")
                        .HasColumnName("achieved_weight");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<string>("PrType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pr_type");

                    b.Property<float>("PrValue")
                        .HasColumnType("real")
                        .HasColumnName("pr_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkoutLogSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_log_set_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutLogSetId");

                    b.HasIndex("UserId", "ExerciseId", "PrType");

                    b.ToTable("exercise_prs", (string)null);
                });

            modelBuilder.Entity("OptiLifts.Domain.Workouts.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("folder_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("folders", (string)null);
                });

            modelBuilder.Entity("OptiLifts.Domain.Workouts.Muscle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("muscle_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("muscles", (string)null);
                });

            modelBuilder.Entity("OptiLifts.Domain.Workouts.ScheduledEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<string>("GoogleEventId")
                        .HasColumnType("text")
                        .HasColumnName("google_event_id");

                    b.Property<DateTime>("Scheduled")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("scheduled_entries", (string)null);
                });

            modelBuilder.Entity("OptiLifts.Domain.Workouts.SecMuscle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("sec_muscle_id");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<Guid>("MuscleId")
                        .HasColumnType("uuid")
                        .HasColumnName("muscle_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("MuscleId");

                    b.ToTable("sec_muscles", (string)null);
                });

            modelBuilder.Entity("OptiLifts.Domain.Workouts.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("workout_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("folder_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("CreatedBy", "IsDeleted");

                    b.ToTable("workouts", (string)null);
                });

            modelBuilder.Entity("OptiLifts.Domain.Workouts.WorkoutExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("workout_exercise_id");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_dict_id");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("GroupId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("workout_exercises", (string)null);
                });

            modelBuilder.Entity("OptiLifts.Domain.Workouts.WorkoutLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("log_id");

                    b.Property<bool>("AiModified")
                        .HasColumnType("boolean")
                        .HasColumnName("ai_modified");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid?>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.ToTable("workout_logs", (string)null);
                });

            modelBuilder.Entity("OptiLifts.Domain.Workouts.WorkoutLogExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("log_exercise_id");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<int>("GroupNumber")
                        .HasColumnType("integer")
                        .HasColumnName("group_number");

                    b.Property<Guid>("LogId")
                        .HasColumnType("uuid")
                        .HasColumnName("log_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<Guid?>("WorkoutExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_exercise_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("LogId", "ExerciseId");

                    b.HasIndex("LogId", "OrderIndex");

                    b.HasIndex("LogId", "WorkoutExerciseId")
                        .IsUnique()
                        .HasFilter("workout_exercise_id IS NOT NULL");

                    b.ToTable("workout_log_exercises", (string)null);
                });

            modelBuilder.Entity("OptiLifts.Domain.Workouts.WorkoutSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("set_id");

                    b.Property<float?>("Distance")
                        .HasColumnType("real")
                        .HasColumnName("distance");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<int?>("Reps")
                        .HasColumnType("integer")
                        .HasColumnName("reps");

                    b.Property<int>("RestTime")
                        .HasColumnType("integer")
                        .HasColumnName("rest_time");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("set_type");

                    b.Property<float?>("Weight")
                        .HasColumnType("real")
                        .HasColumnName("weight");

                    b.Property<Guid>("WorkoutExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_exercise_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutExerciseId");

                    b.ToTable("sets", (string)null);
                });

            modelBuilder.Entity("OptiLifts.Domain.Workouts.WorkoutSetLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("log_set_id");

                    b.Property<bool>("AiSuggested")
                        .HasColumnType("boolean")
                        .HasColumnName("ai_suggested");

                    b.Property<float?>("Distance")
                        .HasColumnType("real")
                        .HasColumnName("distance");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<int>("GroupNumber")
                        .HasColumnType("integer")
                        .HasColumnName("group_number");

                    b.Property<Guid>("LogId")
                        .HasColumnType("uuid")
                        .HasColumnName("log_id");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_at");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<int>("Reps")
                        .HasColumnType("integer")
                        .HasColumnName("reps");

                    b.Property<int>("RestTime")
                        .HasColumnType("integer")
                        .HasColumnName("rest_time");

                    b.Property<float?>("Rpe")
                        .HasColumnType("real")
                        .HasColumnName("rpe");

                    b.Property<Guid?>("SetId")
                        .HasColumnType("uuid")
                        .HasColumnName("set_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("set_type");

                    b.Property<float>("Weight")
                        .HasColumnType("real")
                        .HasColumnName("weight");

                    b.Property<Guid?>("WorkoutExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_exercise_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("LogId");

                    b.ToTable("workout_log_sets", (string)null);
                });

            modelBuilder.Entity("OptiLifts.Domain.Gamification.UserBadge", b =>
                {
                    b.HasOne("OptiLifts.Domain.Gamification.Badge", null)
                        .WithMany()
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OptiLifts.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OptiLifts.Domain.Messaging.Message", b =>
                {
                    b.HasOne("OptiLifts.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OptiLifts.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OptiLifts.Domain.Training.ExerciseTrend", b =>
                {
                    b.HasOne("OptiLifts.Domain.Workouts.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OptiLifts.Domain.Workouts.Exercise", null)
                        .WithMany()
                        .HasForeignKey("SupersedesExerciseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OptiLifts.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OptiLifts.Domain.Training.TrainingEvent", b =>
                {
                    b.HasOne("OptiLifts.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OptiLifts.Domain.Users.UserModel", b =>
                {
                    b.HasOne("OptiLifts.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OptiLifts.Domain.Workouts.Exercise", b =>
                {
                    b.HasOne("OptiLifts.Domain.Workouts.Muscle", null)
                        .WithMany()
                        .HasForeignKey("PrimaryMuscleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OptiLifts.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OptiLifts.Domain.Workouts.ExerciseGroup", b =>
                {
                    b.HasOne("OptiLifts.Domain.Workouts.Workout", null)
                        .WithMany()
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OptiLifts.Domain.Workouts.ExercisePr", b =>
                {
                    b.HasOne("OptiLifts.Domain.Workouts.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OptiLifts.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OptiLifts.Domain.Workouts.WorkoutSetLog", null)
                        .WithMany()
                        .HasForeignKey("WorkoutLogSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OptiLifts.Domain.Workouts.Folder", b =>
                {
                    b.HasOne("OptiLifts.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OptiLifts.Domain.Workouts.ScheduledEntry", b =>
                {
                    b.HasOne("OptiLifts.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OptiLifts.Domain.Workouts.Workout", null)
                        .WithMany()
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OptiLifts.Domain.Workouts.SecMuscle", b =>
                {
                    b.HasOne("OptiLifts.Domain.Workouts.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OptiLifts.Domain.Workouts.Muscle", null)
                        .WithMany()
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OptiLifts.Domain.Workouts.Workout", b =>
                {
                    b.HasOne("OptiLifts.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OptiLifts.Domain.Workouts.Folder", null)
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("OptiLifts.Domain.Workouts.WorkoutExercise", b =>
                {
                    b.HasOne("OptiLifts.Domain.Workouts.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OptiLifts.Domain.Workouts.ExerciseGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OptiLifts.Domain.Workouts.Workout", null)
                        .WithMany()
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OptiLifts.Domain.Workouts.WorkoutLog", b =>
                {
                    b.HasOne("OptiLifts.Domain.Workouts.ScheduledEntry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OptiLifts.Domain.Workouts.WorkoutLogExercise", b =>
                {
                    b.HasOne("OptiLifts.Domain.Workouts.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OptiLifts.Domain.Workouts.WorkoutLog", null)
                        .WithMany()
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OptiLifts.Domain.Workouts.WorkoutSet", b =>
                {
                    b.HasOne("OptiLifts.Domain.Workouts.WorkoutExercise", null)
                        .WithMany()
                        .HasForeignKey("WorkoutExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OptiLifts.Domain.Workouts.WorkoutSetLog", b =>
                {
                    b.HasOne("OptiLifts.Domain.Workouts.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OptiLifts.Domain.Workouts.WorkoutLog", null)
                        .WithMany()
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
